import { useBlockProps } from '@wordpress/block-editor';

export default function save( { attributes } ) {
	const {
		postTypeRestBase,
		taxonomyRestBase,
		taxonomyLabel,
		showCategoryMenu,
		allTermsLabel,
		termOrderBy,
		termOrder,
		perPage,
		columns,
		gap,
		showImage,
		showExcerpt,
		showAuthor,
		showDate,
		showCta,
		orderBy,
		order,
		cardRadius,
		imageRatio,
		imageFit,
		hoverAnimation,
		borderWidth,
		borderStyle,
		borderColor,
		cardBackgroundColor,
		titleFontSize,
		titleColor,
		excerptFontSize,
		excerptColor,
		metaFontSize,
		metaColor,
		pillGap,
		pillRadius,
		pillBackgroundColor,
		pillTextColor,
	} = attributes;

	const blockProps = useBlockProps.save( {
		style: {
			'--rcc-columns': columns,
			'--rcc-gap': `${ gap }px`,
			'--rcc-radius': `${ cardRadius }px`,
			'--rcc-ratio': imageRatio,
			'--rcc-image-fit': imageFit,
			'--rcc-border-width': `${ borderWidth }px`,
			'--rcc-border-style': borderStyle,
			'--rcc-border-color': borderColor || undefined,
			'--rcc-card-bg': cardBackgroundColor || undefined,
			'--rcc-pill-gap': `${ pillGap }px`,
			'--rcc-pill-radius': `${ pillRadius }px`,
			'--rcc-pill-bg': pillBackgroundColor || undefined,
			'--rcc-pill-color': pillTextColor || undefined,
		},
		'data-post-type-rest-base': postTypeRestBase,
		'data-taxonomy-rest-base': taxonomyRestBase,
		'data-taxonomy-label': taxonomyLabel,
		'data-show-category-menu': showCategoryMenu,
		'data-all-terms-label': allTermsLabel,
		'data-term-order-by': termOrderBy,
		'data-term-order': termOrder,
		'data-per-page': perPage,
		'data-order-by': orderBy,
		'data-order': order,
		'data-show-image': showImage,
		'data-show-excerpt': showExcerpt,
		'data-show-author': showAuthor,
		'data-show-date': showDate,
		'data-show-cta': showCta,
		'data-hover-animation': hoverAnimation,
		'data-title-font-size': titleFontSize || '',
		'data-title-color': titleColor,
		'data-excerpt-font-size': excerptFontSize || '',
		'data-excerpt-color': excerptColor,
		'data-meta-font-size': metaFontSize || '',
		'data-meta-color': metaColor,
	} );

	// Markup is a static placeholder only. view.js fetches the live category
	// menu and post grid, and wires the interactive filtering, on the
	// frontend — nothing fetched is ever baked into saved post content.
	return <div { ...blockProps } />;
}
